-- Table: match_statistics.match

-- DROP TABLE IF EXISTS match_statistics.match;

CREATE TABLE IF NOT EXISTS match_statistics.match
(
    match_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    event character varying COLLATE pg_catalog."default",
    match_date date,
    stage character varying COLLATE pg_catalog."default",
    round character varying COLLATE pg_catalog."default",
    match_winner character varying COLLATE pg_catalog."default",
    team_one_name character varying COLLATE pg_catalog."default",
    team_two_name character varying COLLATE pg_catalog."default",
    map_one character varying COLLATE pg_catalog."default",
    map_two character varying COLLATE pg_catalog."default",
    map_three character varying COLLATE pg_catalog."default",
    map_four character varying COLLATE pg_catalog."default",
    map_five character varying COLLATE pg_catalog."default",
    CONSTRAINT match_pkey PRIMARY KEY (match_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS match_statistics.match
    OWNER to batch;