-- Table: match_statistics.match_map_team

DROP TABLE IF EXISTS match_statistics.match_map_team;

CREATE TABLE IF NOT EXISTS match_statistics.match_map_team
(
    match_map_team_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    match_id integer,
    map_name character varying,
    team_name character varying,
    win boolean,
    final_score integer,
    defense_score integer,
    attack_score integer,
    overtime_score integer,
    CONSTRAINT match_map_team_pkey PRIMARY KEY (match_map_team_id),
    CONSTRAINT fk_match_match_map_team FOREIGN KEY (match_id)
        REFERENCES match_statistics.match (match_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS match_statistics.match_map_team
    OWNER to batch;